### ISSUE TITLE
Redundant assert macro

### ISSUE THREAD

**Issue by bangalcat** [nallwhy/doumi_test#1]
Hi! 안녕하세요! 간단하고 좋은 라이브러리 감사합니다! 더 발전해서 많은 기능들이 생기면 좋겠어요 😄

코드가 간단해서 훑어보다가 사소하지만 개선될수 있는 부분을 건의드려요! 

https://github.com/nallwhy/doumi_test/blob/v0.1.2/lib/doumi/test/assertions.ex#L69 코드를 보면 assert 매크로가 쓰이고 있는데, 이 매크로에 대한 모듈 import는 강제로 이뤄지고 있지 않아서, 예를 들어 `use ExUnit.Case`를 쓰지 않은 helper 모듈들에서 해당 매크로 사용시 에러 메시지가 출력돼요

<img width="651" alt="image" src="https://github.com/nallwhy/doumi_test/assets/16166083/597a5357-9103-45c0-bbed-b588793bde6f">

이 부분은 `if`문 대신 `unless`문을 쓰도록 바꾸고 assert true를 빼거나, 매크로 안에 `import ExUnit.Assertions`를 해주면 더 좋지 않을까 싶습니다. 

Btw, I like your efforts and would like to support them. Good luck!

**Comment by nallwhy** [comment]
감사합니다! 불필요하게 `assert true` 를 사용한 것 같아 조언 해주신대로 `unless` 를 이용하는 방식으로 변경하였습니다 ㅎㅎ
v0.1.4 로 릴리즈 되었습니다.
